# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_money',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='订单金额'),
        ),
    ]
